### PR TITLE
added './manage.py cms update_course_settings_from_json' command

### PR DESCRIPTION
**Pull request by a-kryachko**
**Description:** Added manage.py command for CMS to update course settings from JSON

**Youtrack:** https://youtrack.raccoongang.com/issue/DEV-5

**Example of usage:** ```manage.py cms update_course_settings_from_json '{ "start_date": "2017-1-31T00:00:00.000Z" }' 'course-v1:Demo+Demo+course' --settings=aws```

### CODE REVIEW

**Comment by a-kryachko** [comment]
start all tests

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 

<a href='http://localhost:8080/sample/job/edx-platform-quality-flow-pr/15/'>http://localhost:8080/sample/job/edx-platform-quality-flow-pr/15/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/204/'>http://localhost:8080/sample/job/edx-platform-test-subset/204/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/205/'>http://localhost:8080/sample/job/edx-platform-test-subset/205/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/206/'>http://localhost:8080/sample/job/edx-platform-test-subset/206/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/207/'>http://localhost:8080/sample/job/edx-platform-test-subset/207/</a>

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 

<a href='http://localhost:8080/sample/job/edx-platform-bok-choy-pr/15/'>http://localhost:8080/sample/job/edx-platform-bok-choy-pr/15/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/208/'>http://localhost:8080/sample/job/edx-platform-test-subset/208/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/209/'>http://localhost:8080/sample/job/edx-platform-test-subset/209/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/210/'>http://localhost:8080/sample/job/edx-platform-test-subset/210/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/211/'>http://localhost:8080/sample/job/edx-platform-test-subset/211/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/212/'>http://localhost:8080/sample/job/edx-platform-test-subset/212/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/213/'>http://localhost:8080/sample/job/edx-platform-test-subset/213/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/214/'>http://localhost:8080/sample/job/edx-platform-test-subset/214/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/215/'>http://localhost:8080/sample/job/edx-platform-test-subset/215/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/216/'>http://localhost:8080/sample/job/edx-platform-test-subset/216/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/217/'>http://localhost:8080/sample/job/edx-platform-test-subset/217/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/218/'>http://localhost:8080/sample/job/edx-platform-test-subset/218/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/219/'>http://localhost:8080/sample/job/edx-platform-test-subset/219/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/220/'>http://localhost:8080/sample/job/edx-platform-test-subset/220/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/221/'>http://localhost:8080/sample/job/edx-platform-test-subset/221/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/222/'>http://localhost:8080/sample/job/edx-platform-test-subset/222/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/223/'>http://localhost:8080/sample/job/edx-platform-test-subset/223/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/224/'>http://localhost:8080/sample/job/edx-platform-test-subset/224/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/225/'>http://localhost:8080/sample/job/edx-platform-test-subset/225/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/226/'>http://localhost:8080/sample/job/edx-platform-test-subset/226/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/227/'>http://localhost:8080/sample/job/edx-platform-test-subset/227/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/228/'>http://localhost:8080/sample/job/edx-platform-test-subset/228/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/230/'>http://localhost:8080/sample/job/edx-platform-test-subset/230/</a>

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 

<a href='http://localhost:8080/sample/job/edx-platform-lettuce-pr/15/'>http://localhost:8080/sample/job/edx-platform-lettuce-pr/15/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/229/'>http://localhost:8080/sample/job/edx-platform-test-subset/229/</a>
<a href='http://localhost:8080/sample/job/edx-platform-test-subset/231/'>http://localhost:8080/sample/job/edx-platform-test-subset/231/</a>

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins-ci.raccoongang.com/job/edx-platform-js-pr/13/

**Comment by raccoondeploy** [comment]
Refer to this link for build results (access rights to CI server needed): 

<a href='http://jenkins-ci.raccoongang.com/job/ficus-python-unittests-pr/2/'>http://jenkins-ci.raccoongang.com/job/ficus-python-unittests-pr/2/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/64/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/64/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/65/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/65/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/66/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/66/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/67/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/67/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/68/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/68/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/69/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/69/</a>

**Pull request closed without merging**
