### PR TITLE
[CB] Fix bookmark deleted units

### PR DESCRIPTION
**Pull request by arsentur**
**Description:** 
Fix issue when after deleting unit, section, subsection it's stay in bookmarks and link navigate to 404 page.
Added test for new util function.

**Youtrack:** 
https://youtrack.raccoongang.com/issue/CB-86

### CODE REVIEW

**Comment by raccoondeploy** [comment]
Can one of the admins verify this patch?

**Comment by raccoondeploy** [comment]
Can one of the admins verify this patch?

**Comment by raccoondeploy** [comment]
Can one of the admins verify this patch?

**Comment by svic** [comment]
start all tests

**Comment by svic** [comment]
start all tests

**Comment by svic** [comment]
start all tests

**Comment by svic** [comment]
start javascript tests

**Comment by idegtiarov** [comment]
Please do not forget to add the projet's marker in the brackets to the PR's title in current case it should be 
```
[CB] Fix bookmark deleted units
```

**Pull request merged**
