### PR TITLE
Hawthorn rg jenkins

### PR DESCRIPTION
**Pull request by ogrg**
**Description:** Describe in a couple of sentences what this PR adds

**Youtrack:** Link to Youtrack ticket

**Merge deadline:** List merge deadline (if any)

**Configuration instructions:** List any non-trivial configuration
instructions (if any).

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Reviewers:**
- [ ] tag reviewer
- [ ] tag reviewer

**Related Confluence documents:**
- < URL to Confluence document 1 >
- < URL to Confluence document 2 >
- ...
- < URL to Confluence document N >

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Documentation in source code updated
- [ ] All related Confluence documentation is updated (including deployment documentation)
- [ ] Commits are squashed

**Post merge:**
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant
solutions, hacks, quick-and-dirty implementations, concerns about
migrations, etc.

### CODE REVIEW

**Comment by ogrg** [comment]
test

**Comment by ogrg** [comment]
test

**Comment by ogrg** [comment]
test

**Comment by raccoondeploy** [comment]
Refer to this link for build results (access rights to CI server needed): 

<a href='http://jenkins-ci.raccoongang.com/job/hawthorn-python-unittests-pr/2/'>http://jenkins-ci.raccoongang.com/job/hawthorn-python-unittests-pr/2/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/1/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/1/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/2/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/2/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/3/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/3/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/4/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/4/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/5/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/5/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/6/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/6/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/7/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/7/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/8/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/8/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/9/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/9/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/10/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/10/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/11/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/11/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/12/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/12/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/13/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/13/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/14/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/14/</a>
<a href='http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/15/'>http://jenkins-ci.raccoongang.com/job/edx-platform-test-subset/15/</a>

**Pull request closed without merging**
