### PR TITLE
fixed raising exception when empty or incorrect 'course_id' is passed to 'del_course' action

### PR DESCRIPTION
**Pull request by a-kryachko**
RG QA report:

```
1. Go to http://lms.domain/sysadmin
2. Select 'courses'
3. Fill "ID field" or leave it blank and press "Delete Course"
4. See 500 error

Expected behavior: can delete course

Result: Error 500
```

### CODE REVIEW

**Comment by hetmantsev** [comment]
start ci

**Comment by hetmantsev** [comment]
test this please

**Comment by hetmantsev** [comment]
test this please

**Comment by hetmantsev** [comment]
test this please

**Comment by hetmantsev** [comment]
test this please

**Comment by a-kryachko** [comment]
test this please

**Comment by hetmantsev** [comment]
[quality_all] Build failed running pavelib.quality.run_xsslint: XSSLinter Failed.
[quality_all] 
[quality_all] Too many python-concat-html violations (27).
[quality_all] The python-concat-html limit is 25.

**Pull request closed without merging**
