### PR TITLE
Hardskills exam ficus stage

### PR DESCRIPTION
**Pull request by a-kryachko**
**Description:** "Finish Exam" button for the courses

**Youtrack:** [Link to Youtrack ticket](https://youtrack.raccoongang.com/issue/PRESALE_MARKETING-807)

### CODE REVIEW

**Comment by wowkalucky** [comment]
Looks like everything is here...

PS: @a-kryachko who is `barug`?

**Review by wowkalucky — APPROVED** [review]
🤞 
we need to be ready to rollback

**Comment by GlugovGrGlib** [comment]
@wowkalucky it's Bogdan Slusarenko )

**Comment by GlugovGrGlib** [comment]
Merged in https://github.com/raccoongang/edx-platform/pull/2482

**Pull request closed without merging**
