### PR TITLE
fixed raising exception when empty or incorrect 'course_id' is passed to 'del_course' action

### PR DESCRIPTION
**Pull request by a-kryachko**
RG QA report:

```
1. Go to http://lms.domain/sysadmin
2. Select 'courses'
3. Fill "ID field" and press "Delete Course"
4. See 500 error

Expected behavior: can delete course

Result: Error 500
```

### CODE REVIEW

**Comment by hetmantsev** [comment]
test this please

**Comment by hetmantsev** [comment]
OK to test

**Comment by hetmantsev** [comment]
test it please

**Comment by hetmantsev** [comment]
test this please

**Comment by a-kryachko** [comment]
test this please

**Comment by a-kryachko** [comment]
start all tests

**Comment by raccoondeploy** [comment]
start all tests

**Comment by raccoondeploy** [comment]
start all tests

**Pull request closed without merging**
