### PR TITLE
Ginkgo rg fix unit test - paverlib tests

### PR DESCRIPTION
**Pull request by AndreyLykhoman**

### CODE REVIEW

**Comment by hetmantsev** [comment]
codecov/project disabled for this branch. its ok. here is the fix for ficus-rg https://github.com/raccoongang/edx-platform/pull/221

**Comment by AndreyLykhoman** [comment]
@Marx86 @idegtiarov @dgamanenko @sidorovdmitry 
Необходимо ревью кода для PR

**Comment by rimikt** [comment]
@AndreyLykhoman add description and link to the task.

**Comment by hetmantsev** [comment]
@AndreyLykhoman 
Is it mergable or you need to fix smth?

FYI 
To enable codecov/project check merge last ginkgo-rg branch changes in your branch.

**Comment by hetmantsev** [comment]
run unit tests

**Comment by hetmantsev** [comment]
start unit tests

**Comment by hetmantsev** [comment]
already merged. closed.

**Pull request closed without merging**
