### PR TITLE
Add edx basic install xblocks.

### PR DESCRIPTION
**Pull request by dgamanenko**
Ficus rg base xblocks

qa: https://youtrack.raccoongang.com/issue/DIDACTICUM-15

### CODE REVIEW

**Comment by hetmantsev** [comment]
start quality tests

**Comment by hetmantsev** [comment]
start unit tests

**Comment by hetmantsev** [comment]
start unit tests

**Comment by hetmantsev** [comment]
start unit tests

**Comment by a-kryachko** [comment]
start all tests

**Pull request closed without merging**
