### PR TITLE
Test commit #1

### PR DESCRIPTION
**Pull request by svic**
test open-release/ Hawthorn.master

### CODE REVIEW

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins-ci.raccoongang.com/job/edx-platform-accessibility-pr/9/

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins-ci.raccoongang.com/job/edx-platform-js-pr/9/

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins-ci.raccoongang.com/job/hawthorn-js-pr/1/

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins-ci.raccoongang.com/job/hawthorn-accessibility-pr/1/

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins-ci.raccoongang.com/job/hawthorn-js-pr/2/

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins-ci.raccoongang.com/job/hawthorn-js-pr/3/

**Comment by Alexei-Kornienko** [comment]
run python tests

**Comment by Alexei-Kornienko** [comment]
hawthorn run python

**Comment by Alexei-Kornienko** [comment]
hawthorn run js

**Comment by Alexei-Kornienko** [comment]
hawthorn run js

**Comment by svic** [comment]
hawthorn run js

**Comment by svic** [comment]
hawthorn run js

**Comment by svic** [comment]
hawthorn run js

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins-ci.raccoongang.com/job/hawthorn-js-pr/4/

**Comment by svic** [comment]
hawthorn run js

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins-ci.raccoongang.com/job/hawthorn-js-pr/5/

**Comment by Alexei-Kornienko** [comment]
hawthorn run js

**Comment by svic** [comment]
hawthorn run js

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins-ci.raccoongang.com/job/hawthorn-js-pr/6/

**Comment by svic** [comment]
hawthorn run js

**Comment by svic** [comment]
Refer to this link for build results (access rights to CI server needed): 
jenkins-ci.raccoongang.com/job/hawthorn-js-pr/7/

**Pull request closed without merging**
