### PR TITLE
Base install/fixing search

### PR DESCRIPTION
**Pull request by a-kryachko**
**Description:** Preparation for enabling edx-search on edx-platform. Appling fixes for known bugs.

**Youtrack:** https://youtrack.raccoongang.com/issue/DOI-68

**Configuration instructions:** To enable edx-search on edx-platform add to EDXAPP_FEATURES dictionary next variables:

```
  ENABLE_COURSEWARE_INDEX: true
  ENABLE_LIBRARY_INDEX: true
  ENABLE_COURSEWARE_SEARCH: true
  ENABLE_DASHBOARD_SEARCH: true
  ENABLE_COURSE_DISCOVERY: true
```

**Reviewers:**
- [ ] @raccoongang/devops 

**Merge checklist:**
- [ ] All reviewers approved
- [x] CI build is green
- [x] Commits are squashed
- [x] https://github.com/raccoongang/configuration/pull/80 is merged

**Post merge:**
- [ ] Delete working branch (if not needed anymore)

### CODE REVIEW

**Comment by hetmantsev** [comment]
start unit tests

**Comment by a-kryachko** [comment]
start unit tests

**Comment by hetmantsev** [comment]
start unit tests

**Comment by hetmantsev** [comment]
start unit tests

**Comment by hetmantsev** [comment]
start unit tests

**Comment by a-kryachko** [comment]
start unit tests, please, dear microsoft

**Comment by a-kryachko** [comment]
@AndreyLykhoman please review the code

**Pull request merged**
